### ISSUE TITLE
ENH Implement new stage coordinates metadata

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/pims_nd2#2]
The current one is wrong. There has been a fix in the new SDK but it needs an extra function wrapped.

**Comment by caspervdw** [comment]
This leaves Lim_GetStageCoordinates, Lim_SetStageAlignment, Lim_GetAlignmentPoints unimplemented.

**Comment by mahdilamb** [comment]
Hi Casper,

I'm not sure if this is the right place to post, but I have implemented Lim_GetStageCoordinates in a project which I'm working on and wanted to provide that code. 

In the ND2SDK.py file, I've added:

`Lim_GetStageCoordinates = nd2.Lim_GetStageCoordinates
Lim_GetStageCoordinates.argtypes = [LIMFILEHANDLE, LIMUINT, POINTER(LIMUINT),POINTER(LIMUINT),POINTER(LIMUINT), POINTER(c_double),POINTER(c_double),POINTER(c_double),LIMBOOL]
Lim_GetStageCoordinates.restype = LIMRESULT`

And in nd2reader.py:
`_stagex = h.c_double(.0)
        _stagey = h.c_double(.0)
        _stagez = h.c_double(.0)
        h.Lim_GetStageCoordinates(self._handle, h.LIMUINT(int(1)), h.LIMUINT(int(i)), h.c_ulong(attr.uiWidth >> 1), h.c_ulong(attr.uiHeight >> 1), _stagex,_stagey,_stagez,h.LIMBOOL(bool(1)))
        metadata = {
                    'stage_coords': {'x': _stagex.value, 'y': _stagey.value, 'z': _stagez.value}}`
